# theme.toml template for a Hugo theme
name = "Roxo Hugo"
license = "GNU General Public License"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.html"
description = "Roxo Hugo is a digital agency Hugo theme for creative agencies,  freelancers, graphic designers, photographers. Can be used for any kind of corporate websites who provides digital services with many expertise such as  Design, Digital Products, Development, Campaign & Content, Employer Branding, Animation & Motion Graphics ,Packaging & Product Design, Retail & Spacial, Print & Editorial Design, Concept/Text, Information Design etc. "
homepage = "https://roxo-hugo.staticmania.com/"
tags = ['clean', 'minimal', 'agency', 'corporate', 'creative agency', 'creative studio', 'portfolio', 'staticmania', 'responsive', 'blog', 'customizable', 'company', 'creative', 'agency template']
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive','landing-page', 'minimal', 'business', 'agency-template', 'hugo-theme', 'portfolio', 'company', 'creative', 'contact-form']
min_version = "0.58.0"

[author]
  name = "Static Mania"
  homepage = "https://staticmania.com/"
